import type {
  CadenceRun,
  Comment,
  ContentItem,
  DepartmentRequest,
  OperatingCadence,
  Person,
  RaciAssignment,
  Stage,
} from './content-types';
import { PIPELINE } from './content-types';

export const demoPeople: Person[] = [
  {
    id: 'p1',
    name: 'Workspace Owner 1',
    email: 'owner.one@aafmindia.test',
    initials: 'O1',
    roles: ['Owner'],
    isActive: true,
    responsibility: 'Protected full-access ID',
  },
  {
    id: 'p2',
    name: 'Priya',
    email: 'priya@aafmindia.test',
    initials: 'PR',
    roles: ['Admin', 'Content Approver'],
    isActive: true,
    responsibility: 'Strategy, calendar supervision and final brand approval',
  },
  {
    id: 'p3',
    name: 'Chhahal',
    email: 'chhahal@aafmindia.test',
    initials: 'CH',
    roles: ['Content Producer', 'Monitoring'],
    isActive: true,
    responsibility: 'Publishing, calendar and performance reporting',
  },
  {
    id: 'p4',
    name: 'Harshit',
    email: 'harshit@aafmindia.test',
    initials: 'HA',
    roles: ['Content Producer', 'Content Approver'],
    isActive: true,
    responsibility:
      'Content, scripts, creatives, recording and quality control',
  },
  {
    id: 'p5',
    name: 'Piyush',
    email: 'piyush@aafmindia.test',
    initials: 'PI',
    roles: ['Content Producer'],
    isActive: true,
    responsibility: 'Reels, podcasts and short-form repurposing',
  },
  {
    id: 'p6',
    name: 'Kapil',
    email: 'kapil@aafmindia.test',
    initials: 'KA',
    roles: ['Content Producer'],
    isActive: true,
    responsibility: 'Static creatives, LinkedIn posts and carousels',
  },
  {
    id: 'p7',
    name: 'Jai',
    email: 'jai@aafmindia.test',
    initials: 'JA',
    roles: ['Content Producer'],
    isActive: true,
    responsibility: 'Video shoots, equipment, course videos and testimonials',
  },
  {
    id: 'p8',
    name: 'Pawas / KM',
    email: 'compliance@aafmindia.test',
    initials: 'KM',
    roles: ['Content Approver'],
    isActive: true,
    responsibility: 'Technical accuracy and financial compliance',
  },
  {
    id: 'p9',
    name: 'Department HODs',
    email: 'hod.requests@aafmindia.test',
    initials: 'HD',
    roles: ['Content Producer'],
    isActive: true,
    responsibility: 'Topic research and subject-matter inputs',
  },
  {
    id: 'p10',
    name: 'Workspace Owner 2',
    email: 'owner.two@aafmindia.test',
    initials: 'O2',
    roles: ['Owner'],
    isActive: true,
    responsibility: 'Protected full-access ID',
  },
];

const [
  ownerOne,
  priya,
  chhahal,
  harshit,
  piyush,
  kapil,
  jai,
  compliance,
  hods,
  ownerTwo,
] = demoPeople;

type ContentItemBeforeRaci = Omit<
  ContentItem,
  'consulted' | 'informed' | 'raci' | 'comments'
> & { comments: Array<Omit<Comment, 'stage' | 'kind' | 'resolved'>> };

const demoItemsBeforeRaci: ContentItemBeforeRaci[] = [
  {
    id: 'c1',
    title: 'CWM: Career paths in private banking',
    contentType: 'Reel',
    platform: 'Instagram',
    pillar: 'Knowledge',
    workflowStep: 'Financial compliance',
    stage: 'Script',
    status: 'Pending approval',
    dueAt: '2026-09-11T12:30:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [harshit],
    accountable: [compliance, priya],
    secondLens: 'Awaiting review',
    links: [
      {
        label: 'Working script',
        kind: 'Script',
        url: 'https://docs.google.com/',
      },
    ],
    history: [
      { action: 'Item created', actor: 'Harshit', at: '8 Sep · 10:20 AM' },
      {
        action: 'Idea approved → Script',
        actor: 'Priya',
        at: '8 Sep · 4:45 PM',
      },
      {
        action: 'Script sent for compliance',
        actor: 'Harshit',
        at: 'Today · 11:10 AM',
      },
    ],
    comments: [
      {
        id: 'm1',
        author: 'Pawas / KM',
        initials: 'KM',
        body: 'Please qualify the return illustration and retain the education-only disclaimer.',
        at: '12:10 PM',
      },
    ],
    metrics: [],
  },
  {
    id: 'c2',
    title: 'Estate planning myths: carousel',
    contentType: 'Carousel',
    platform: 'LinkedIn',
    pillar: 'Knowledge',
    workflowStep: 'Harshit quality check',
    stage: 'Production',
    status: 'Pending approval',
    dueAt: '2026-09-11T16:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [kapil],
    accountable: [harshit, priya],
    secondLens: 'Approved',
    links: [
      {
        label: 'Approved script',
        kind: 'Script',
        url: 'https://docs.google.com/',
      },
      {
        label: 'Design draft',
        kind: 'Creative',
        url: 'https://drive.google.com/',
      },
    ],
    history: [
      {
        action: 'Financial compliance approved',
        actor: 'Pawas / KM',
        at: '9 Sep · 3:12 PM',
      },
      {
        action: 'Production submitted for quality check',
        actor: 'Kapil',
        at: 'Today · 9:25 AM',
      },
    ],
    comments: [
      {
        id: 'm2',
        author: 'Harshit',
        initials: 'HA',
        body: 'Slides 4–6 are clear. Checking mobile legibility before final sign-off.',
        at: '9:40 AM',
      },
    ],
    metrics: [],
  },
  {
    id: 'c3',
    title: 'September admissions campaign calendar',
    contentType: 'Post',
    platform: 'Multi-platform',
    pillar: 'Promotional',
    workflowStep: 'Calendar slot',
    stage: 'Idea',
    status: 'In progress',
    dueAt: '2026-09-12T11:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [chhahal],
    accountable: [priya],
    secondLens: 'Not needed',
    links: [
      {
        label: 'Monthly calendar',
        kind: 'Calendar',
        url: 'https://docs.google.com/',
      },
    ],
    history: [
      {
        action: 'Topic set received from admissions',
        actor: 'Chhahal',
        at: 'Today · 10:15 AM',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c4',
    title: 'Inside the Wealth & Alternates Convention',
    contentType: 'Video',
    platform: 'YouTube',
    pillar: 'AAFM India Insider',
    workflowStep: 'Recording',
    stage: 'Shoot',
    status: 'In progress',
    dueAt: '2026-09-12T15:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [jai, harshit],
    accountable: [priya],
    secondLens: 'Not needed',
    links: [
      { label: 'Shoot brief', kind: 'Brief', url: 'https://docs.google.com/' },
    ],
    history: [
      {
        action: 'Shoot brief approved',
        actor: 'Harshit',
        at: '9 Sep · 5:42 PM',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c5',
    title: 'CFP vs CWM: which path fits whom?',
    contentType: 'Short',
    platform: 'YouTube',
    pillar: 'Knowledge',
    workflowStep: 'Subject-matter validation',
    stage: 'Script',
    status: 'Changes requested',
    dueAt: '2026-09-10T18:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [piyush],
    accountable: [compliance],
    secondLens: 'Changes requested',
    links: [
      { label: 'Script v2', kind: 'Script', url: 'https://docs.google.com/' },
    ],
    history: [
      {
        action: 'Subject-matter changes requested',
        actor: 'Pawas / KM',
        at: 'Today · 4:08 PM',
        note: 'Separate the course comparison from individual career advice.',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c6',
    title: 'Student testimonial: first role after CWM',
    contentType: 'Reel',
    platform: 'Instagram',
    pillar: 'AAFM India Insider',
    workflowStep: 'Priya final approval',
    stage: 'Production',
    status: 'Pending approval',
    dueAt: '2026-09-12T17:30:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [piyush],
    accountable: [harshit, priya],
    secondLens: 'Approved',
    links: [
      {
        label: 'Edit v3',
        kind: 'Edited video',
        url: 'https://drive.google.com/',
      },
    ],
    history: [
      {
        action: 'Harshit quality check approved',
        actor: 'Harshit',
        at: 'Today · 2:05 PM',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c7',
    title: 'Financial literacy week: daily tips',
    contentType: 'Post',
    platform: 'Instagram',
    pillar: 'Knowledge',
    workflowStep: 'Platform scheduling',
    stage: 'Upload',
    status: 'In progress',
    dueAt: '2026-09-11T09:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [chhahal],
    accountable: [priya],
    secondLens: 'Not needed',
    links: [
      {
        label: 'Final artwork',
        kind: 'Creative',
        url: 'https://drive.google.com/',
      },
    ],
    history: [
      {
        action: 'Final brand approval recorded',
        actor: 'Priya',
        at: 'Today · 10:02 AM',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c8',
    title: 'Executive program enrolment deadline',
    contentType: 'Post',
    platform: 'LinkedIn',
    pillar: 'Promotional',
    workflowStep: 'Publishing',
    stage: 'Upload',
    status: 'Pending approval',
    dueAt: '2026-09-10T22:30:00+05:30',
    reminderHours: 6,
    lifecycle: 'Active',
    responsible: [chhahal],
    accountable: [priya],
    secondLens: 'Not needed',
    links: [
      {
        label: 'Scheduled post',
        kind: 'Publishing',
        url: 'https://linkedin.com/company/aafmindia/',
      },
    ],
    history: [
      {
        action: 'Scheduled and submitted for publish approval',
        actor: 'Chhahal',
        at: 'Today · 6:45 PM',
      },
    ],
    comments: [],
    metrics: [],
  },
  {
    id: 'c9',
    title: 'How compounding changes long-term outcomes',
    contentType: 'Reel',
    platform: 'Instagram',
    pillar: 'Knowledge',
    workflowStep: 'Performance snapshot',
    stage: 'Post-Upload',
    status: 'In progress',
    dueAt: '2026-09-11T13:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [chhahal],
    accountable: [chhahal],
    secondLens: 'Not needed',
    publishedAt: '2026-09-10T09:12:00+05:30',
    links: [
      {
        label: 'Published reel',
        kind: 'Published post',
        url: 'https://instagram.com/aafm.india/',
      },
    ],
    history: [{ action: 'Published', actor: 'Chhahal', at: 'Today · 9:12 AM' }],
    comments: [],
    metrics: [],
  },
  {
    id: 'c10',
    title: 'Three portfolio mistakes new advisors make',
    contentType: 'Post',
    platform: 'LinkedIn',
    pillar: 'Knowledge',
    workflowStep: 'Weekly or monthly reporting',
    stage: 'Post-Upload',
    status: 'In progress',
    dueAt: '2026-09-13T12:00:00+05:30',
    reminderHours: 24,
    lifecycle: 'Active',
    responsible: [chhahal],
    accountable: [chhahal, ownerOne],
    secondLens: 'Approved',
    publishedAt: '2026-09-09T08:45:00+05:30',
    links: [
      {
        label: 'Published post',
        kind: 'Published post',
        url: 'https://linkedin.com/company/aafmindia/',
      },
    ],
    history: [
      { action: 'Published', actor: 'Chhahal', at: 'Yesterday · 8:45 AM' },
    ],
    comments: [],
    metrics: [
      {
        id: 'me1',
        platform: 'LinkedIn',
        contentUrl: 'https://linkedin.com/company/aafmindia/',
        views: 8240,
        reach: 6910,
        impressions: 9420,
        likes: 311,
        comments: 26,
        shares: 49,
        saves: 34,
        watchTimeMinutes: 0,
        followerChange: 18,
        notes: 'Educational list format outperformed the weekly average.',
        source: 'Manual',
        recordedOn: '2026-09-10',
      },
    ],
  },
];

const defaultRaci: Record<Stage, RaciAssignment> = {
  Idea: {
    responsible: [chhahal, harshit],
    accountable: [priya],
    consulted: [hods],
    informed: [ownerOne, ownerTwo],
  },
  Script: {
    responsible: [harshit, piyush],
    accountable: [compliance, priya],
    consulted: [hods],
    informed: [chhahal],
  },
  Shoot: {
    responsible: [jai, harshit],
    accountable: [priya],
    consulted: [piyush],
    informed: [chhahal, ownerOne],
  },
  Production: {
    responsible: [piyush, kapil],
    accountable: [harshit, priya],
    consulted: [compliance],
    informed: [chhahal],
  },
  Upload: {
    responsible: [chhahal],
    accountable: [priya],
    consulted: [harshit],
    informed: [ownerOne, ownerTwo],
  },
  'Post-Upload': {
    responsible: [chhahal],
    accountable: [priya],
    consulted: [harshit],
    informed: [ownerOne, ownerTwo],
  },
};

export const demoItems: ContentItem[] = demoItemsBeforeRaci.map((item) => {
  const raci = Object.fromEntries(
    PIPELINE.map((stage) => [
      stage,
      stage === item.stage
        ? {
            responsible: item.responsible,
            accountable: item.accountable,
            consulted: defaultRaci[stage].consulted,
            informed: defaultRaci[stage].informed,
          }
        : defaultRaci[stage],
    ]),
  ) as Record<Stage, RaciAssignment>;
  return {
    ...item,
    comments: item.comments.map((comment) => ({
      ...comment,
      stage: item.stage,
      kind: 'Update' as const,
      resolved: false,
    })),
    consulted: raci[item.stage].consulted,
    informed: raci[item.stage].informed,
    raci,
  };
});

export const demoCadences: OperatingCadence[] = [
  {
    id: 'cad-6',
    name: 'Script and compliance review',
    purpose:
      'Review technical accuracy, disclaimers and subject-matter inputs before recording.',
    frequency: 'Weekly',
    weekday: 2,
    time: '11:30',
    timezone: 'Asia/Kolkata',
    owner: compliance,
    participants: [priya, harshit, hods],
    stage: 'Script',
    deliverable:
      'Compliance decisions and script revisions logged on each content item',
    reminderHours: 24,
    active: true,
  },
  {
    id: 'cad-7',
    name: 'Shoot and production handoff',
    purpose: 'Confirm shoot briefs, recording capacity and edit dependencies.',
    frequency: 'Weekly',
    weekday: 3,
    time: '10:30',
    timezone: 'Asia/Kolkata',
    owner: jai,
    participants: [harshit, piyush, kapil],
    stage: 'Shoot',
    deliverable: 'Shoot plan and footage handoff ready for production',
    reminderHours: 24,
    active: true,
  },
  {
    id: 'cad-8',
    name: 'Publishing readiness check',
    purpose:
      'Check approved assets, platform schedules and published-link tracking.',
    frequency: 'Weekly',
    weekday: 5,
    time: '10:00',
    timezone: 'Asia/Kolkata',
    owner: chhahal,
    participants: [priya, harshit],
    stage: 'Upload',
    deliverable:
      'Approved publishing slots with final files and tracked live links',
    reminderHours: 24,
    active: true,
  },
  {
    id: 'cad-1',
    name: 'Weekly content planning',
    purpose:
      'Confirm priorities, owners, dependencies and deadlines for the next seven days.',
    frequency: 'Weekly',
    weekday: 1,
    time: '10:30',
    timezone: 'Asia/Kolkata',
    owner: priya,
    participants: [chhahal, harshit, hods],
    stage: 'Idea',
    deliverable: 'Approved weekly priority list and updated content calendar',
    reminderHours: 24,
    active: true,
  },
  {
    id: 'cad-2',
    name: 'Approval and publishing readiness',
    purpose:
      'Clear compliance, creative and publishing blockers before the weekly release window.',
    frequency: 'Weekly',
    weekday: 4,
    time: '15:30',
    timezone: 'Asia/Kolkata',
    owner: harshit,
    participants: [priya, compliance, chhahal],
    stage: 'Production',
    deliverable:
      'Decision log for every item due to publish in the next seven days',
    reminderHours: 6,
    active: true,
  },
  {
    id: 'cad-3',
    name: 'Weekly performance pulse',
    purpose:
      'Capture platform results, lessons and follow-up actions in the unified report.',
    frequency: 'Weekly',
    weekday: 5,
    time: '16:30',
    timezone: 'Asia/Kolkata',
    owner: chhahal,
    participants: [priya, harshit],
    stage: 'Post-Upload',
    deliverable: 'Weekly performance snapshot with learning notes',
    reminderHours: 24,
    active: true,
  },
  {
    id: 'cad-4',
    name: 'Monthly editorial calendar',
    purpose: 'Lock next month’s topics, content mix and production capacity.',
    frequency: 'Monthly',
    dayOfMonth: 25,
    time: '11:00',
    timezone: 'Asia/Kolkata',
    owner: priya,
    participants: [chhahal, harshit, hods],
    stage: 'Idea',
    deliverable: 'Approved monthly calendar with the 60/20/20 content mix',
    reminderHours: 48,
    active: true,
  },
  {
    id: 'cad-5',
    name: 'Monthly content and analytics review',
    purpose:
      'Review content mix, platform performance and next-month experiments.',
    frequency: 'Monthly',
    dayOfMonth: 2,
    time: '15:00',
    timezone: 'Asia/Kolkata',
    owner: chhahal,
    participants: [priya, harshit, ownerOne, ownerTwo],
    stage: 'Post-Upload',
    deliverable:
      'Monthly report, content-mix variance and three agreed experiments',
    reminderHours: 48,
    active: true,
  },
];

export const demoCadenceRuns: CadenceRun[] = [];

export const demoRequests: DepartmentRequest[] = [
  {
    id: 'r1',
    department: 'Admissions',
    requester: 'Neha',
    request: 'Four creatives for the October CWM intake',
    priority: 'Urgent',
    neededBy: '15 Sep',
    status: 'Accepted',
  },
  {
    id: 'r2',
    department: 'Academic Team',
    requester: 'Dr. Rao',
    request: 'Promote the new risk-management masterclass',
    priority: 'Normal',
    neededBy: '20 Sep',
    status: 'New',
  },
  {
    id: 'r3',
    department: 'Events',
    requester: 'Sahil',
    request: 'Speaker clips from the Wealth Convention',
    priority: 'Normal',
    neededBy: '18 Sep',
    status: 'Scheduled',
  },
];
