-- Give the first Owner a realistic, immediately usable workspace.
-- All identifiers are generated by Postgres and captured inside this short
-- transaction; the migration does not depend on environment-specific UUIDs.
begin;

do $$
declare
  owner_profile uuid;
  idea_item uuid;
  script_item uuid;
  shoot_item uuid;
  production_item uuid;
  upload_item uuid;
  post_upload_item uuid;
  seeded_item_ids uuid[];
begin
  select p.id
    into owner_profile
  from public.profiles p
  where lower(p.email) = 'aditi@buildablelabs.com'
    and p.is_active
  limit 1;

  if owner_profile is null then
    raise exception 'The designated Owner profile must exist before seeding the workspace';
  end if;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, created_by
  ) values (
    'September admissions campaign calendar',
    'Post', 'Multi-platform', 'promotional', 'Confirm campaign themes and priority dates',
    'idea', 'in_progress', now() + interval '2 days', 24, owner_profile
  ) returning id into idea_item;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, created_by
  ) values (
    'CFP vs CWM: which path fits whom?',
    'Short', 'YouTube', 'knowledge', 'Subject-matter and compliance review',
    'script', 'pending_approval', now() + interval '3 days', 24, owner_profile
  ) returning id into script_item;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, created_by
  ) values (
    'Inside the Wealth & Alternates Convention',
    'Short', 'YouTube', 'aafm_india_insider', 'Record speaker-led event highlights',
    'shoot', 'in_progress', now() + interval '5 days', 24, owner_profile
  ) returning id into shoot_item;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, created_by
  ) values (
    'Estate planning myths: carousel',
    'Carousel', 'LinkedIn', 'knowledge', 'Revise the creative after quality review',
    'production', 'changes_requested', now() + interval '6 days', 24, owner_profile
  ) returning id into production_item;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, created_by
  ) values (
    'Executive program enrolment deadline',
    'Post', 'LinkedIn', 'promotional', 'Final publishing-readiness check',
    'upload', 'pending_approval', now() + interval '8 days', 24, owner_profile
  ) returning id into upload_item;

  insert into public.content_items (
    title, content_type, platform, content_pillar, workflow_step,
    current_stage, stage_status, due_at, reminder_hours_before, published_at, created_by
  ) values (
    'How compounding changes long-term outcomes',
    'Reel', 'Instagram', 'knowledge', 'Capture learning notes after publication',
    'post_upload_metrics', 'in_progress', now() + interval '10 days', 24,
    now() - interval '1 day', owner_profile
  ) returning id into post_upload_item;

  seeded_item_ids := array[
    idea_item, script_item, shoot_item, production_item, upload_item, post_upload_item
  ];

  -- Until the team accepts invitations, the protected Owner fills each RACI
  -- slot so every handoff is demonstrable. Admins can replace these stage by
  -- stage as real colleagues join.
  insert into public.item_stage_assignments (
    content_item_id, stage, profile_id, assignment_type
  )
  select
    item_id,
    stage_name,
    owner_profile,
    assignment_name
  from unnest(seeded_item_ids) as seeded(item_id)
  cross join unnest(enum_range(null::public.pipeline_stage)) as stages(stage_name)
  cross join unnest(enum_range(null::public.assignment_type)) as assignments(assignment_name);

  -- Seeded ownership is orientation data, not a real assignment event. Remove
  -- the trigger-created notifications (and their cascading email outbox rows)
  -- so the Owner's first session starts clean.
  delete from public.notifications
  where content_item_id = any(seeded_item_ids)
    and kind = 'raci_assigned';

  insert into public.stage_history (
    content_item_id, from_stage, to_stage, action, actor_id, note, metadata
  )
  select
    i.id,
    null,
    i.current_stage,
    'created',
    owner_profile,
    'Demo item created for the initial workspace walkthrough',
    jsonb_build_object('seeded_demo', true)
  from public.content_items i
  where i.id = any(seeded_item_ids);

  insert into public.stage_reviews (
    content_item_id, stage, reviewer_id, decision, note
  ) values
    (script_item, 'script', owner_profile, 'pending',
      'Confirm that the comparison is factual, neutral and suitable for a first-time learner.'),
    (production_item, 'production', owner_profile, 'changes_requested',
      'Make the disclaimer easier to read and reduce the copy on slide four.');

  insert into public.comments (
    content_item_id, author_id, body, stage, kind
  ) values
    (script_item, owner_profile,
      'Please validate the programme terminology and keep the comparison educational rather than promotional.',
      'script', 'feedback'),
    (production_item, owner_profile,
      'Revision brief logged: enlarge the disclaimer, simplify slide four and upload the new export here.',
      'production', 'update'),
    (upload_item, owner_profile,
      'Final caption and publishing slot must be confirmed before this moves to Post-Upload.',
      'upload', 'decision');

  insert into public.department_requests (
    department, requester_name, request_text, priority, needed_by, status, created_by
  ) values
    ('Admissions', 'Admissions team',
      'Create four coordinated assets for the next CWM intake campaign.',
      'urgent', current_date + 7, 'accepted', owner_profile),
    ('Academic Team', 'Programme faculty',
      'Build an educational post introducing the risk-management masterclass.',
      'normal', current_date + 12, 'new', owner_profile),
    ('Events', 'Events team',
      'Repurpose the strongest speaker clips from the Wealth & Alternates Convention.',
      'normal', current_date + 14, 'scheduled', owner_profile);

  insert into public.operating_cadences (
    name, purpose, frequency, weekday, day_of_month, time_of_day,
    owner_id, stage, deliverable, reminder_hours_before, created_by
  ) values
    ('Weekly content planning',
      'Confirm priorities, owners, dependencies and deadlines for the next seven days.',
      'weekly', 1, null, '10:30', owner_profile, 'idea',
      'Approved weekly priority list and an updated content calendar', 24, owner_profile),
    ('Script and compliance review',
      'Review technical accuracy, disclaimers and subject-matter inputs before recording.',
      'weekly', 2, null, '11:30', owner_profile, 'script',
      'Compliance decisions and script revisions logged on each content item', 24, owner_profile),
    ('Shoot and production handoff',
      'Confirm shoot briefs, recording capacity and edit dependencies.',
      'weekly', 3, null, '10:30', owner_profile, 'shoot',
      'Shoot plan and footage handoff ready for production', 24, owner_profile),
    ('Approval and publishing readiness',
      'Clear creative, compliance and publishing blockers before the release window.',
      'weekly', 4, null, '15:30', owner_profile, 'production',
      'A recorded decision for every item due to publish in the next seven days', 6, owner_profile),
    ('Publishing readiness check',
      'Check approved assets, platform schedules and published-link tracking.',
      'weekly', 5, null, '10:00', owner_profile, 'upload',
      'Approved publishing slots with final files and tracked live links', 24, owner_profile),
    ('Weekly learning pulse',
      'Record post-publication lessons and follow-up actions without duplicating Zoho reporting.',
      'weekly', 5, null, '16:30', owner_profile, 'post_upload_metrics',
      'Learning notes and follow-up actions attached to the relevant content items', 24, owner_profile),
    ('Monthly editorial calendar',
      'Lock the next month''s topics, content mix and production capacity.',
      'monthly', null, 25, '11:00', owner_profile, 'idea',
      'Approved monthly calendar with the 60/20/20 content mix', 48, owner_profile),
    ('Monthly content retrospective',
      'Review the content mix, delivery bottlenecks and next-month experiments.',
      'monthly', null, 2, '15:00', owner_profile, 'post_upload_metrics',
      'Content-mix variance, delivery lessons and three agreed experiments', 48, owner_profile);

  insert into public.cadence_participants (cadence_id, profile_id)
  select c.id, owner_profile
  from public.operating_cadences c
  where c.created_by = owner_profile
    and c.name in (
      'Weekly content planning',
      'Script and compliance review',
      'Shoot and production handoff',
      'Approval and publishing readiness',
      'Publishing readiness check',
      'Weekly learning pulse',
      'Monthly editorial calendar',
      'Monthly content retrospective'
    );
end;
$$;

commit;
